"""Self-contained delivery desk. Current forecasts and historical experiments are separate."""
from html import escape
import json

from .daily_session_view import STYLE


def render(data):
    payload=json.dumps(data,ensure_ascii=False,allow_nan=False).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    return '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'none'; form-action 'self'; base-uri 'none'">
<title>Stock Data · 研究与每日复盘</title>'''+STYLE+'''
<style>.tabs{display:flex;gap:24px;border-bottom:1px solid #bbb;padding:15px 0}.tabs a{color:#28574b}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:25px 0}.metrics article{border-top:2px solid #263b36;padding:14px 0}.metrics b{display:block;font:30px Georgia,serif}th{white-space:nowrap}.scroll{overflow:auto}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #b56f3b;outline-offset:2px}.small{font-size:13px;color:#5a645e}.toolbar{display:flex;align-items:center;gap:20px;flex-wrap:wrap}.badge{border:1px solid #6d8979;padding:4px 10px}#current tbody tr{cursor:pointer}#current tbody tr:hover{background:#e6eadf}#message{white-space:pre-wrap;color:#96502d}.note{border-left:3px solid #406052;padding:12px;margin:12px 0}summary{padding:10px 0}@media(max-width:650px){.metrics{grid-template-columns:repeat(2,1fr)}.tabs{gap:12px;font-size:14px}}</style>
<main><header><span class="eyebrow">STOCK DATA / LOCAL RESEARCH DESK</span><h1>研究有结果，判断有记录。</h1><p>当前预测 · 来源与风险 · 人工判断 · 后续复盘</p><span class="badge">本地研究版 / 不连接交易</span></header>
<nav class="tabs"><a href="#today">今日观察</a><a href="#experiment">QLib对照</a><a href="#journal">判断记录</a><a href="#followup">后续复盘</a></nav>
<p id="message"><!--SERVER_MESSAGE--></p><section class="metrics" id="stats"></section>
<section id="today"><div class="toolbar"><h2>当前研究候选</h2><form method="post" action="/update"><input type="hidden" name="csrf" value="__CSRF__"><button>更新真实数据与预测</button></form></div>
<p id="freshness" class="small"></p><p class="warning">模型评分是下一交易日开盘至T+2收盘的价格变化估计，不是成交承诺或收益保证。当前历史对照未证明选股优势，以下是研究观察清单，不是买入推荐。缺失记录保留；当前模型预先指定为价格基线，不按测试赢家自动切换。</p>
<div class="toolbar"><label>筛选证券 <input id="search" placeholder="输入代码或名称，点击行查看依据" maxlength="30"></label><label>排序依据 <select id="sort"><option value="model">QLib价格模型</option><option value="rule">20日动量规则（不训练）</option></select></label></div>
<div class="scroll"><table id="current"><thead><tr><th>证券</th><th>模型估计 %</th><th>20日动量 %</th><th>数据状态</th></tr></thead><tbody></tbody></table></div><p id="empty"></p>
<details id="details"><summary>选中候选的依据与风险</summary><div id="evidence"></div></details></section>
<section id="experiment"><h2>历史研究：共同样本对照</h2><p id="scope" class="small"></p><div class="scroll"><table><thead><tr><th>模型组</th><th>样本 / 日期</th><th>MSE</th><th>日均Rank IC</th><th>Top5价格目标均值 %</th></tr></thead><tbody id="models"></tbody></table></div>
<p class="small">同一组样本、同一目标和预处理规则。资金与Alpha158的对照结果允许为负；Top5统计不是资金曲线。尾段不评分、不调参。历史可用性选择存在偏差，不能外推全市场。</p><div id="comparison"></div></section>
<section id="journal"><h2>记录你的判断</h2><p class="small">署名为你自行声明；保存时记录本机接收时间，不生成委托。原记录不可改写。</p>
<p id="note-context" class="small"></p><form method="post" action="/note" id="note-form"><input type="hidden" name="csrf" value="__CSRF__"><input type="hidden" name="prediction_id" id="prediction-id"><input type="hidden" name="supersedes" id="supersedes">
<div class="layout"><div><label>证券 <select name="instrument" id="instrument"></select></label><label>署名 <input name="operator" required maxlength="200"></label><label>意向 <select name="intent"><option value="observe">继续观察</option><option value="reject">不采用</option><option value="paper_hypothesis">研究假设（不下单）</option></select></label></div><div><label>判断依据 <textarea name="hypothesis" required maxlength="4000"></textarea></label><label>失效条件 <textarea name="invalidation" required maxlength="4000"></textarea></label></div></div><button id="save">保存判断到本地</button> <button type="button" id="new-note">退出修订，记录当前判断</button></form><div id="notes"></div></section>
<section id="followup"><h2>冻结预测与后续结果</h2><p>只评价先冻结、后实际收到的价格。尚未成熟和精确会话缺价分别保留；不补零、不把新训练结果回填旧预测。</p><div id="reviews"></div></section>
<footer>离线显示数据全部内联。研究样本与真实账户分开；未验证选股优势，真实执行关闭。<!--RUNNING_REFRESH--></footer></main>
<script type="application/json" id="data">'''+payload+'''</script><script>
'use strict';const D=JSON.parse(document.getElementById('data').textContent),$=x=>document.getElementById(x),P=D.prediction;
const el=(tag,t)=>{const e=document.createElement(tag);e.textContent=t;return e},fmt=x=>x==null?'—':Number(x).toFixed(4);
const labels={price_baseline:'QLib · 价格',price_money:'QLib · 价格 + 资金',price_alpha158:'QLib · 价格 + Alpha158',constant:'常量预测（误差对照）'};
const featureNames={ret_1d:'1日涨跌幅 %',ret_5d:'5日涨跌幅 %',ret_20d:'20日涨跌幅 %',volatility_20d:'20日波动率',intraday_range:'当日振幅 / 收盘价',volume_ratio_20d:'成交量 / 20日均量',money_ratio:'当日净流入 / 成交额',money_ratio_5d:'5日净流入 / 成交额',base_value:'模型起始值'};
const gapNames={source_price_conflict:'双来源价格或量额冲突',missing_dual_source_price:'缺少双来源价格',daily_factor_missing:'缺复权因子',identity_snapshot_missing_or_outside_listing:'身份或上市期间不足',nonpositive_volume:'无有效成交量'};
const gaps=g=>Object.entries(g||{}).map(([k,v])=>(gapNames[k]||k)+' '+v+'日').join('；')||'无';
const rows=P?P.rows:[];function table(target,items){target.replaceChildren(...items.map(values=>{const tr=el('tr','');values.forEach(v=>tr.append(el('td',v)));return tr}))}
[['历史研究证券',D.dataset.summary.universe_count],['滚动对照折数',D.research.folds.length],['当前非空预测',P?P.predictions:0],['判断记录',D.notes.length]].forEach(([a,b])=>{const s=el('article',a);s.append(el('b',b));$('stats').append(s)});
$('scope').textContent=D.dataset.dataset_config.start+' → '+D.dataset.dataset_config.end+'；'+D.dataset.rows+'行特征；事后取得的探索数据，不是原时点回放。';
$('freshness').textContent=P?'行情日期 '+P.date+' / 数据接收 '+(P.data_received_at||P.captured_at)+' / 本次冻结 '+P.captured_at+' / 模型训练截至 '+P.model_train_end+(P.receipt_replay?' / 原始回执重放':'')+(P.prospective_eligible===false?' / 已错过目标开盘，不计前瞻成绩':P.forecast_status==='pending_future_calendar'?' / 等待未来交易日日历核对，未计前瞻成绩':'')+(P.model_id!==D.model.model_id?' / 当前预测属于上一冻结模型，请更新':''):'尚未获取当前预测。下方历史实验已完成。';
function show(r){$('details').open=true;const evidence=$('evidence');evidence.replaceChildren(el('h3',r.instrument),el('p',r.prediction==null?'未进入模型观察清单：当前依赖窗口不足，不补值。':'进入观察清单的原因：21日价格依赖完整，冻结QLib模型可计算非空评分；不代表已验证买入机会。'),el('p','QLib价格目标估计 '+fmt(r.prediction)+'%；独立动量规则 '+fmt(r.baseline_momentum_20d)+'%。前者预测短期目标，后者只按过去20日涨跌排序。'),el('p','近21日缺口：'+gaps(r.active_window_gap_counts)+'。完整采集窗口缺口：'+gaps(r.window_gap_counts)),el('p','价格 / 资金 / Alpha158窗口：'+['price_eligible','money_eligible','alpha158_window_eligible'].map(k=>r.eligibility?.[k]?'足够':'不足').join(' / ')+'。Alpha158窗口足够不等于已产生当前Alpha158预测。'));
const t=el('table','');const body=el('tbody','');t.append(body);table(body,Object.entries(r.features).map(([k,v])=>[featureNames[k]||k,fmt(v)]));evidence.append(t,el('h3','评分的主要贡献'));
Object.entries(r.contributions||{}).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).forEach(([k,v])=>evidence.append(el('p',(featureNames[k]||k)+'：'+(v>=0?'+':'')+fmt(v)+'个百分点')));
evidence.append(el('p','贡献项之和等于评分，不是因果解释。风险：模型老化、样本选择偏差、跳空及无法成交，价格目标不是组合收益。请自行填写失效条件，系统不会替你作出判断。'));
const d=el('details','');d.append(el('summary','来源回执'),el('p','同花顺原生价格；中继日线交叉核对、复权与资金。'),el('pre',JSON.stringify(r.receipt_files,null,2)));evidence.append(d);if(!$('supersedes').value)$('instrument').value=r.instrument}
function draw(){const key=$('sort').value==='rule'?'baseline_momentum_20d':'prediction';const filtered=rows.filter(r=>(r.instrument+' '+(r.name||'')).includes($('search').value.trim())).slice().sort((a,b)=>(a[key]==null)-(b[key]==null)||(b[key]||0)-(a[key]||0)||a.instrument.localeCompare(b.instrument));table($('current').tBodies[0],filtered.map(r=>[r.instrument+' '+(r.name||''),fmt(r.prediction),fmt(r.baseline_momentum_20d),r.prediction==null?'特征不足':'研究预测']));[...$('current').tBodies[0].rows].forEach((tr,i)=>{tr.tabIndex=0;tr.onclick=()=>show(filtered[i]);tr.onkeydown=e=>{if(e.key==='Enter')tr.click()}});$('empty').textContent=filtered.length?'':'当前无可展示候选'}draw();$('search').oninput=draw;$('sort').onchange=draw;
table($('models'),Object.entries(D.research.aggregate).map(([k,v])=>[labels[k]||k,v.samples+' / '+v.days,fmt(v.mse),fmt(v.mean_daily_rank_ic),fmt(v.top_k_mean_label_pct)]));
if(D.rule_baselines){const b=D.rule_baselines.summary;[['动量规则（无训练）',b.mean_daily_rank_ic,b.momentum_top5_target_pct],['共同证券等权观察',null,b.equal_weight_target_pct]].forEach(([name,ic,value])=>{const tr=el('tr','');[name,b.samples+' / '+b.days,'不适用',fmt(ic),fmt(value)].forEach(v=>tr.append(el('td',v)));$('models').append(tr)});$('comparison').append(el('p','规则对照复用每折完全相同的样本身份；动量分数不冒充收益预测，因此不计算其MSE。等权行使用全部共同证券，不是Top5。规则为事后明确的固定规则，不宣称未见样本。'))}
Object.entries(D.research.paired_comparisons).forEach(([k,v])=>$('comparison').append(el('p',(labels[k]||k)+' 相对价格基线日MSE差 '+fmt(v.mean_daily_mse_difference)+'；描述性区间 '+(v.moving_block_bootstrap_95pct||[]).map(fmt).join(' ～ ')+'（负值较好）')));
if(D.previous_model_comparison){const c=D.previous_model_comparison,v=c.old_frozen_model,tr=el('tr','');['旧冻结价格模型（训练截至 '+c.previous_train_end+'）',v.samples+' / '+v.days,fmt(v.mse),fmt(v.mean_daily_rank_ic),fmt(v.top_k_mean_label_pct)].forEach(x=>tr.append(el('td',x)));$('models').append(tr);$('comparison').append(el('p','旧模型复用新滚动实验的完全相同测试身份；这是近期历史对照，不是未来实盘成绩。近期候选模型另按固定60日训练、15日验证拟合，不使用最后20日留出标签，也不把训练内结果当成样本外表现。'));}
const candidate=D.candidate_model||D.model;
if(candidate.refit_boundaries)$('comparison').append(el('p','近期候选模型训练截至 '+candidate.train_end+'，验证截至 '+candidate.validation_end+'；独立留出从 '+candidate.refit_boundaries.holdout_start+' 开始，未参与最终拟合。'));
if(D.candidate_readiness&&!D.candidate_readiness.can_replace_current_model){const q=D.candidate_readiness;$('comparison').append(el('p','近期模型未替换当前模型：测试日每天仅 '+q.minimum_test_cross_section+'～'+q.maximum_test_cross_section+' 只，需要至少 '+q.required_minimum_cross_section+' 只才能检验Top5选择；新模型当前非空 '+q.current_nonempty+' 只，原版 '+q.previous_nonempty+' 只。上方继续展示旧模型预测，重训产物保留。'));if(q.minimum_test_cross_section<q.required_minimum_cross_section)[...$('models').rows].forEach(tr=>{if(!tr.cells[0].textContent.includes('等权'))tr.cells[4].textContent='不适用：共同候选不足'});}
if(P?.latest_session_certified===false)$('freshness').append(' / 按封存训练回执重算，未重新认证最新交易日；日期保持为 '+P.date);
rows.forEach(r=>{const o=el('option',r.instrument);o.value=r.instrument;$('instrument').append(o)});$('prediction-id').value=P?P.prediction_id:'';$('save').disabled=!P;
const timingNames={before_entry:'事前判断',after_entry:'事后补记',timing_unverified:'时间资格待核对'};
function resetNote(){$('note-form').reset();$('prediction-id').value=P?P.prediction_id:'';$('supersedes').value='';$('note-context').textContent='绑定当前预测 '+(P?P.prediction_id.slice(0,12):'无')+'；以保存时刻区分事前与事后，不可回填时间。'}resetNote();$('new-note').onclick=resetNote;
D.notes.forEach(n=>{const e=el('div','');e.className='note';e.append(el('strong',n.instrument+' · '+n.operator+' · '+n.received_at),el('p',(timingNames[n.timing]||'旧记录，时间待核对')+' / '+(n.is_latest?'当前记录':'历史版本')+' / '+n.prediction_id.slice(0,12)),el('p',n.hypothesis),el('p','失效：'+n.invalidation));if(n.is_latest){const b=el('button','追加修订，保留原文');b.type='button';b.onclick=()=>{const form=$('note-form');for(const k of ['operator','hypothesis','invalidation','intent'])form.elements[k].value=n[k];if(![...$('instrument').options].some(o=>o.value===n.instrument))$('instrument').append(new Option(n.instrument,n.instrument));$('instrument').value=n.instrument;$('prediction-id').value=n.prediction_id;$('supersedes').value=n.note_id;$('note-context').textContent='修订 '+n.note_id.slice(0,12)+'，仍绑定原预测；事后修订不替代事前判断。';$('journal').scrollIntoView()};e.append(b)}$('notes').append(e)});
const states={pending_exact_future_sessions:'等待后续交易日',mature:'价格目标已成熟',partial_missing_prices:'部分精确价格缺失',outside_current_receipt_window:'超出本次更新窗口',not_prospective:'非事前冻结，不计成绩'};
(D.reviews||[]).forEach(r=>{const e=el('details','');e.append(el('summary',r.prediction_date+' / '+r.prediction_id.slice(0,10)+' / '+(states[r.status]||r.status)+' / 配对 '+r.paired),el('p',r.count_in_summary?'同日同模型首个冻结批次，计入该组统计':'附加判断关联批次，不重复计入统计'));if(r.comparison)e.append(el('p','共同成熟证券 '+r.common_rule_model_samples+' 只；QLib Top5目标均值 '+fmt(r.comparison.model_top5_target_pct)+'%，动量Top5 '+fmt(r.comparison.momentum_top5_target_pct)+'%，等权 '+fmt(r.comparison.equal_weight_target_pct)+'%。不是投资组合收益。'));r.rows.forEach(row=>{const box=el('div','');box.className='note';box.append(el('strong',row.instrument+' / '+row.entry_date+' → '+row.exit_date),el('p','冻结估计 '+fmt(row.prediction)+'%；实际价格目标 '+fmt(row.target_pct)+'%；误差 '+fmt(row.error_pct)+'个百分点'));(row.judgements||[]).forEach(n=>box.append(el('p',(timingNames[n.verified_timing]||'时间待核对')+' · '+n.operator+'：'+n.hypothesis+'；失效条件：'+n.invalidation)));if(row.judgements?.length)box.append(el('p','失效条件是否触发须人工核对，不能仅凭收益正负自动判定。'));e.append(box)});$('reviews').append(e)});if(!(D.reviews||[]).length)$('reviews').textContent='没有成熟的前瞻结果；等待冻结预测之后的实际交易日。';
if(location.protocol==='file:'){document.querySelectorAll('form button').forEach(b=>b.disabled=true);$('message').textContent='离线快照：启动 Start Research.cmd 后可以更新和保存判断。'}
</script></html>'''


def server_page(html, token, message='', running=False):
    return html.replace('__CSRF__',escape(token,quote=True)).replace('<!--SERVER_MESSAGE-->',escape(message)).replace('__SERVER_MESSAGE__',escape(message)).replace(
        '<!--RUNNING_REFRESH-->','<script>setTimeout(()=>{if(!document.querySelector("form :focus"))location.reload()},10000)</script>' if running else '')
